import { Col, Container, Row } from "react-bootstrap";
import styles from "../../../styles/variables.module.scss";

export const metadata = {
    title: "About Page | Click First",
    description: "Generated by create next app",
};
const Page = () => {
    return (
        <section className={styles.homeSec}>
            <Container>
                <Row>
                    <Col>
                        <h1>About Page</h1>
                    </Col>
                </Row>
            </Container>
        </section>
    )
}

export default Page